### ISSUE TITLE
Rust文档中的一点问题和一点建议

### ISSUE THREAD

**Issue by gloit042** [noirgif/ustc-compiler-pointer#1]
1. Box<T>的标题markdown格式不对
2. 它能直接用是因为它是struct 并不是引用....只是封装了一个引用，它打印时通过Box<T>实现的fmt::Display中的fmt函数来输出
3. 可以再讲一下Rc或者Arc 它们是有引用计数的

**Comment by noirgif** [comment]
已修正标题格式和Box的内容。
